In [2]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [33]:
df=pd.read_csv(r"C:\Users\Dayanand\Desktop\Python\ML Projects\Python_Project_9_Ran.csv")
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,03/07/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,06/09/2017
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,07/09/2017
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,07/09/2017
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,07/09/2017
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,07/09/2017

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 23.7+ MB

In [13]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

In [6]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [34]:
df=df.drop("company", axis=1)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,01/07/2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,02/07/2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,02/07/2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,03/07/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,06/09/2017
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,07/09/2017
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,07/09/2017
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,07/09/2017
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,07/09/2017

In [35]:
df=df.dropna(subset=["country"])
df.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
country                               0
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             16006
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

In [36]:
df=df.dropna(subset=["children"])

In [37]:
df["agent"]=df["agent"].fillna(df["agent"].mean())
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

In [38]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,3,No Deposit,86.545532,0,Transient,0.00,0,0,Check-Out,01/07/2015
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,4,No Deposit,86.545532,0,Transient,0.00,0,0,Check-Out,01/07/2015
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,No Deposit,86.545532,0,Transient,75.00,0,0,Check-Out,02/07/2015
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,No Deposit,304.000000,0,Transient,75.00,0,0,Check-Out,02/07/2015
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,0,No Deposit,240.000000,0,Transient,98.00,0,1,Check-Out,03/07/2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,0,No Deposit,394.000000,0,Transient,96.14,0,0,Check-Out,06/09/2017
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,0,No Deposit,9.000000,0,Transient,225.43,0,2,Check-Out,07/09/2017
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,0,No Deposit,9.000000,0,Transient,157.71,0,4,Check-Out,07/09/2017
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,0,No Deposit,89.000000,0,Transient,104.40,0,0,Check-Out,07/09/2017
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,0,No Deposit,9.000000,0,Transient,151.20,0,2,Check-Out,07/09/2017

In [39]:
df["reservation_status_day"]=pd.to_datetime(df.reservation_status_date, format="%d/%m/%Y").dt.day
df["reservation_status_month"]=pd.to_datetime(df.reservation_status_date, format="%d/%m/%Y").dt.month
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,reservation_status_day,reservation_status_month
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,86.545532,0,Transient,0.00,0,0,Check-Out,01/07/2015,1,7
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,86.545532,0,Transient,0.00,0,0,Check-Out,01/07/2015,1,7
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,86.545532,0,Transient,75.00,0,0,Check-Out,02/07/2015,2,7
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,304.000000,0,Transient,75.00,0,0,Check-Out,02/07/2015,2,7
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,240.000000,0,Transient,98.00,0,1,Check-Out,03/07/2015,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,394.000000,0,Transient,96.14,0,0,Check-Out,06/09/2017,6,9
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,9.000000,0,Transient,225.43,0,2,Check-Out,07/09/2017,7,9
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,9.000000,0,Transient,157.71,0,4,Check-Out,07/09/2017,7,9
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,89.000000,0,Transient,104.40,0,0,Check-Out,07/09/2017,7,9
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,9.000000,0,Transient,151.20,0,2,Check-Out,07/09/2017,7,9

In [43]:
df=df.drop("reservation_status_date", axis=1)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_day,reservation_status_month
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,86.545532,0,Transient,0.00,0,0,Check-Out,1,7
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,86.545532,0,Transient,0.00,0,0,Check-Out,1,7
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,86.545532,0,Transient,75.00,0,0,Check-Out,2,7
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.000000,0,Transient,75.00,0,0,Check-Out,2,7
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.000000,0,Transient,98.00,0,1,Check-Out,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.000000,0,Transient,96.14,0,0,Check-Out,6,9
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.000000,0,Transient,225.43,0,2,Check-Out,7,9
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.000000,0,Transient,157.71,0,4,Check-Out,7,9
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.000000,0,Transient,104.40,0,0,Check-Out,7,9
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.000000,0,Transient,151.20,0,2,Check-Out,7,9

In [44]:
df.loc[:, "adults":"deposit_type"]

,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type
0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit
1,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit
2,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit
3,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit
4,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit
119386,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit
119387,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit
119388,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit
119389,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit

In [45]:
df["hotel"]=LabelEncoder().fit_transform(df["hotel"])
df["arrival_date_month"]=LabelEncoder().fit_transform(df["arrival_date_month"])
df["meal"]=LabelEncoder().fit_transform(df["meal"])
df["country"]=LabelEncoder().fit_transform(df["country"])
df["market_segment"]=LabelEncoder().fit_transform(df["market_segment"])
df["distribution_channel"]=LabelEncoder().fit_transform(df["distribution_channel"])
df["reserved_room_type"]=LabelEncoder().fit_transform(df["reserved_room_type"])
df["assigned_room_type"]=LabelEncoder().fit_transform(df["assigned_room_type"])
df["deposit_type"]=LabelEncoder().fit_transform(df["deposit_type"])
df["customer_type"]=LabelEncoder().fit_transform(df["customer_type"])
df["reservation_status"]=LabelEncoder().fit_transform(df["reservation_status"])
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_day,reservation_status_month
0,1,0,342,2015,5,27,1,0,0,2,...,0,86.545532,0,2,0.00,0,0,1,1,7
1,1,0,737,2015,5,27,1,0,0,2,...,0,86.545532,0,2,0.00,0,0,1,1,7
2,1,0,7,2015,5,27,1,0,1,1,...,0,86.545532,0,2,75.00,0,0,1,2,7
3,1,0,13,2015,5,27,1,0,1,1,...,0,304.000000,0,2,75.00,0,0,1,2,7
4,1,0,14,2015,5,27,1,0,2,2,...,0,240.000000,0,2,98.00,0,1,1,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,0,23,2017,1,35,30,2,5,2,...,0,394.000000,0,2,96.14,0,0,1,6,9
119386,0,0,102,2017,1,35,31,2,5,3,...,0,9.000000,0,2,225.43,0,2,1,7,9
119387,0,0,34,2017,1,35,31,2,5,2,...,0,9.000000,0,2,157.71,0,4,1,7,9
119388,0,0,109,2017,1,35,31,2,5,2,...,0,89.000000,0,2,104.40,0,0,1,7,9
119389,0,0,205,2017,1,35,29,2,7,2,...,0,9.000000,0,2,151.20,0,2,1,7,9

In [46]:
df.corr()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_day,reservation_status_month
hotel,1.000000,-0.133964,-0.071867,-0.033765,-0.035517,-0.000730,0.002104,0.189729,0.237769,0.017771,...,-0.157512,0.720242,-0.072015,-0.047156,-0.093156,0.217404,0.044005,0.121814,0.016385,-0.005516
is_canceled,-0.133964,1.000000,0.291994,0.016412,-0.001745,0.007465,-0.006127,-0.002631,0.024110,0.058381,...,0.468497,-0.076959,0.054016,-0.068768,0.046199,-0.194796,-0.235643,-0.917223,-0.034062,-0.069364
lead_time,-0.071867,0.291994,1.000000,0.039924,0.086126,0.126738,0.002320,0.083984,0.164783,0.116799,...,0.375216,-0.064424,0.170007,0.072846,-0.066381,-0.115561,-0.096536,-0.301119,-0.007908,0.055688
arrival_date_year,-0.033765,0.016412,0.039924,1.000000,-0.251447,-0.540493,-0.000590,0.021669,0.031754,0.029146,...,-0.064902,0.059131,-0.056823,-0.006000,0.197857,-0.012661,0.108927,-0.017337,0.024897,-0.358955
arrival_date_month,-0.035517,-0.001745,0.086126,-0.251447,1.000000,0.301967,-0.018136,-0.032010,-0.026019,-0.058890,...,0.067925,-0.037744,0.048464,0.011897,-0.109569,-0.019368,-0.052959,-0.001537,0.004401,0.229328
arrival_date_week_number,-0.000730,0.007465,0.126738,-0.540493,0.301967,1.000000,0.066839,0.017642,0.015007,0.025394,...,0.003484,-0.028174,0.022993,-0.028728,0.075277,0.001717,0.025778,-0.016828,0.009799,0.678734
arrival_date_day_of_month,0.002104,-0.006127,0.002320,-0.000590,-0.018136,0.066839,1.000000,-0.015920,-0.027608,-0.001837,...,-0.001443,0.001613,0.022737,0.012195,0.029923,0.008262,0.003082,0.011415,0.316301,-0.008441
stays_in_weekend_nights,0.189729,-0.002631,0.083984,0.021669,-0.032010,0.017642,-0.015920,1.000000,0.494888,0.090410,...,-0.112170,0.132554,-0.054568,-0.110190,0.047300,-0.018147,0.071669,0.009453,0.013315,0.003826
stays_in_week_nights,0.237769,0.024110,0.164783,0.031754,-0.026019,0.015007,-0.027608,0.494888,1.000000,0.091999,...,-0.077783,0.171019,-0.002161,-0.128539,0.063628,-0.024378,0.066785,-0.020919,0.004336,0.004749
adults,0.017771,0.058381,0.116799,0.029146,-0.058890,0.025394,-0.001837,0.090410,0.091999,1.000000,...,-0.029124,-0.027222,-0.008765,-0.102810,0.227480,0.016370,0.121815,-0.070332,-0.019882,-0.004084
children,0.045414,0.004751,-0.038335,0.054492,-0.082961,0.005494,0.014562,0.045430,0.044259,0.029590,...,-0.096402,0.039597,-0.033396,-0.053542,0.325034,0.057060,0.081786,-0.003117,0.009904,-0.006629
babies,0.043669,-0.032521,-0.021149,-0.013183,-0.012203,0.010039,-0.000539,0.018396,0.020157,0.017887,...,-0.030513,0.033703,-0.010648,-0.016142,0.028591,0.036971,0.097601,0.031006,-0.003319,0.006635
meal,-0.006100,-0.018657,-0.000648,0.065335,-0.062464,-0.017623,-0.007229,0.044637,0.035776,0.025500,...,-0.092620,-0.046963,-0.007311,0.044469,0.057806,-0.038140,0.022586,0.016356,-0.005022,-0.020475
country,0.041322,0.270225,0.054327,-0.153267,0.026656,0.025984,-0.000613,-0.128054,-0.121237,-0.108308,...,0.325354,0.058857,0.060944,0.026969,-0.114451,0.000966,-0.165690,-0.246247,-0.023876,0.010810
market_segment,-0.077571,0.056948,0.009220,0.107001,-0.051836,-0.001011,-0.004183,0.114059,0.107874,0.204186,...,-0.188147,-0.043113,-0.042468,-0.167773,0.229673,-0.059591,0.275206,-0.059222,0.000058,-0.037857
distribution_channel,-0.167916,0.165539,0.217012,0.020912,-0.021192,0.005258,0.001640,0.091167,0.085842,0.173667,...,0.090936,-0.090191,0.048235,-0.071290,0.087430,-0.129835,0.098341,-0.169313,-0.004126,-0.023736
is_repeated_guest,0.051349,-0.085179,-0.125091,0.010128,-0.002049,-0.030411,-0.006340,-0.087836,-0.097994,-0.147494,...,-0.057720,0.019659,-0.022322,-0.017245,-0.135388,0.077776,0.013151,0.083877,-0.000293,-0.009358
previous_cancellations,0.012332,0.109922,0.085961,-0.119922,0.040267,0.035367,-0.027013,-0.013008,-0.014274,-0.006974,...,0.139557,-0.010325,0.005927,-0.008368,-0.065930,-0.018455,-0.048585,-0.110580,-0.010437,-0.008648
previous_bookings_not_canceled,-0.000747,-0.055493,-0.071128,0.029800,-0.003386,-0.020768,0.000118,-0.040597,-0.047367,-0.105028,...,-0.030425,0.005947,-0.009011,-0.011539,-0.069638,0.046945,0.037595,0.053279,-0.001953,-0.010135
reserved_room_type,0.252234,-0.062230,-0.107036,0.092999,-0.062569,-0.008544,0.017143,0.141700,0.168662,0.211998,...,-0.200266,0.195767,-0.069047,-0.121283,0.393011,0.131736,0.136845,0.059593,0.012720,-0.024957
assigned_room_type,0.307582,-0.175880,-0.171187,0.036661,-0.037398,-0.005064,0.012054,0.087755,0.102137,0.148282,...,-0.242382,0.218346,-0.068642,-0.084240,0.261755,0.158898,0.124826,0.172397,0.018700,-0.009919
booking_changes,0.073159,-0.144659,0.000004,0.031124,-0.017963,0.005187,0.010767,0.062401,0.095665,-0.052420,...,-0.112293,0.059745,-0.011661,0.092182,0.019201,0.065724,0.052434,0.141052,0.023281,0.011443
deposit_type,-0.157512,0.468497,0.375216,-0.064902,0.067925,0.003484,-0.001443,-0.112170,-0.077783,-0.029124,...,1.000000,-0.092934,0.120946,-0.076577,-0.091193,-0.090538,-0.267344,-0.466044,-0.027171,0.007605
agent,0.720242,-0.076959,-0.064424,0.059131,-0.037744,-0.028174,0.001613,0.132554,0.171019,-0.027222,...,-0.092934,1.000000,-0.054588,0.045982,-0.021910,0.151863,0.031779,0.070481,0.019974,-0.006352
days_in_waiting_list,-0.072015,0.054016,0.170007,-0.056823,0.048464,0.022993,0.022737,-0.054568,-0.002161,-0.008765,...,0.120946,-0.054588,1.000000,0.099134,-0.041333,-0.030462,-0.082970,-0.057771,0.023118,0.017492
customer_type,-0.047156,-0.068768,0.072846,-0.006000,0.011897,-0.028728,0.012195,-0.110190,-0.128539,-0.102810,...,-0.076577,0.045982,0.099134,1.000000,-0.077908,-0.030054,-0.135958,0.066623,0.026599,0.010691
adr,-0.093156,0.046199,-0.066381,0.197857,-0.109569,0.075277,0.029923,0.047300,0.063628,0.227480,...,-0.091193,-0.021910,-0.041333,-0.077908,1.000000,0.058053,0.171458,-0.049305,0.012180,0.010350
required_car_parking_spaces,0.217404,-0.194796,-0.115561,-0.012661,-0.019368,0.001717,0.008262,-0.018147,-0.024378,0.016370,...,-0.090538,0.151863,-0.030462,-0.030054,0.058053,1.000000,0.082675,0.178671,0.005987,0.014173
total_of_special_requests,0.044005,-0.235643,-0.096536,0.108927,-0.052959,0.025778,0.003082,0.071669,0.066785,0.121815,...,-0.267344,0.031779,-0.082970,-0.135958,0.171458,0.082675,1.000000,0.226603,0.006636,0.056346
reservation_status,0.121814,-0.917223,-0.301119,-0.017337,-0.001537,-0.016828,0.011415,0.009453,-0.020919,-0.070332,...,-0.466044,0.070481,-0.057771,0.066623,-0.049305,0.178671,0.226603,1.000000,0.039172,0.060206
reservation_status_day,0.016385,-0.034062,-0.007908,0.024897,0.004401,0.009799,0.316301,0.013315,0.004336,-0.019882,...,-0.027171,0.019974,0.023118,0.026599,0.012180,0.005987,0.006636,0.039172,1.000000,0.026235
reservation_status_month,-0.005516,-0.069364,0.055688,-0.358955,0.229328,0.678734,-0.008441,0.003826,0.004749,-0.004084,...,0.007605,-0.006352,0.017492,0.010691,0.010350,0.014173,0.056346,0.060206,0.026235,1.000000

In [48]:
x=df.drop(["arrival_date_month","stays_in_weekend_nights","children", "is_canceled"], axis=1)
x

,hotel,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_week_nights,adults,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_day,reservation_status_month
0,1,342,2015,27,1,0,2,0,0,135,...,0,86.545532,0,2,0.00,0,0,1,1,7
1,1,737,2015,27,1,0,2,0,0,135,...,0,86.545532,0,2,0.00,0,0,1,1,7
2,1,7,2015,27,1,1,1,0,0,59,...,0,86.545532,0,2,75.00,0,0,1,2,7
3,1,13,2015,27,1,1,1,0,0,59,...,0,304.000000,0,2,75.00,0,0,1,2,7
4,1,14,2015,27,1,2,2,0,0,59,...,0,240.000000,0,2,98.00,0,1,1,3,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,0,23,2017,35,30,5,2,0,0,15,...,0,394.000000,0,2,96.14,0,0,1,6,9
119386,0,102,2017,35,31,5,3,0,0,56,...,0,9.000000,0,2,225.43,0,2,1,7,9
119387,0,34,2017,35,31,5,2,0,0,43,...,0,9.000000,0,2,157.71,0,4,1,7,9
119388,0,109,2017,35,31,5,2,0,0,59,...,0,89.000000,0,2,104.40,0,0,1,7,9
119389,0,205,2017,35,29,7,2,0,2,43,...,0,9.000000,0,2,151.20,0,2,1,7,9

In [49]:
y=df["is_canceled"]
y

0         0
1         0
2         0
3         0
4         0
         ..
119385    0
119386    0
119387    0
119388    0
119389    0
Name: is_canceled, Length: 118898, dtype: int64

In [51]:
cols=x.columns
cols

Index(['hotel', 'lead_time', 'arrival_date_year', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_week_nights', 'adults', 'babies',
       'meal', 'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_day',
       'reservation_status_month'],
      dtype='object')

In [52]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2)

In [53]:
x_train.shape, x_test.shape

((95118, 28), (23780, 28))

In [54]:
x_train=StandardScaler().fit_transform(x_train)
x_train=pd.DataFrame(x_train, columns=[cols])
x_train

,hotel,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_week_nights,adults,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_day,reservation_status_month
0,-0.705468,-0.762332,-0.223699,1.240647,1.276407,-0.789728,1.985080,-0.080103,-0.521776,-1.744203,...,-0.373829,0.304878,-0.131825,-0.239057,0.343841,-0.252142,0.538555,0.704596,1.405380,1.096490
1,-0.705468,-0.921527,1.191236,0.504442,1.048581,-0.789728,0.246307,-0.080103,-0.521776,0.939963,...,-0.373829,0.000292,-0.131825,-0.239057,1.316439,-0.252142,0.538555,0.704596,1.177539,0.498063
2,-0.705468,-0.294111,1.191236,-1.115208,0.706842,0.788788,0.246307,-0.080103,-0.521776,-1.117898,...,-0.373829,-0.750612,-0.131825,-0.239057,-0.030687,-0.252142,-0.721407,-1.304571,-0.759111,-1.596430
3,-0.705468,0.595510,1.191236,0.136340,0.137278,0.262616,0.246307,-0.080103,-0.521776,-1.744203,...,-0.373829,-0.750612,-0.131825,-0.239057,0.102653,-0.252142,0.538555,0.704596,0.607936,0.198850
4,1.417498,0.389492,-1.638634,1.167026,0.365104,1.314960,-1.492466,-0.080103,-0.521776,-0.760009,...,-0.373829,1.486253,-0.131825,-0.239057,-1.047797,-0.252142,1.798517,0.704596,1.177539,1.096490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95113,1.417498,-0.331568,-0.223699,0.946165,1.618146,-0.789728,0.246307,-0.080103,-0.521776,1.700476,...,-0.373829,1.486253,-0.131825,-0.239057,0.728174,-0.252142,-0.721407,-1.304571,0.835777,0.198850
95114,1.417498,0.782798,-0.223699,-0.599865,-1.343590,0.788788,0.246307,-0.080103,-0.521776,0.939963,...,-0.373829,1.486253,-0.131825,-0.239057,-0.591500,3.848251,-0.721407,0.704596,-0.873032,-0.399577
95115,-0.705468,-0.434577,-1.638634,1.240647,1.618146,-0.789728,-1.492466,-0.080103,-0.521776,0.939963,...,-0.373829,-0.750612,-0.131825,-3.706363,-0.320898,-0.252142,1.798517,0.704596,1.747142,1.096490
95116,1.417498,-0.378390,-1.638634,0.430822,-0.204461,0.262616,1.985080,-0.080103,1.345603,-0.938953,...,-0.373829,0.537280,-0.131825,-0.239057,1.302321,3.848251,1.798517,0.704596,0.380095,0.498063
95117,1.417498,1.269748,-0.223699,1.093406,-0.432287,2.367305,0.246307,-0.080103,-0.521776,-0.760009,...,-0.373829,0.000292,-0.131825,-0.239057,-0.409138,-0.252142,-0.721407,0.704596,0.607936,1.096490

In [55]:
x_test=StandardScaler().fit_transform(x_test)
x_test=pd.DataFrame(x_test, columns=[cols])
x_test

,hotel,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_week_nights,adults,babies,meal,country,...,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_day,reservation_status_month
0,1.406046,0.783056,-0.219471,0.937058,1.044191,3.946273,0.238811,-0.088383,-0.517330,-0.382309,...,-0.373935,1.603180,-0.135269,-0.234109,0.251211,-0.258658,-0.720427,0.706416,-0.761213,1.094511
1,-0.711214,-0.520924,-1.627357,1.083938,-0.207680,0.786243,0.238811,-0.088383,-0.517330,0.941915,...,-0.373935,-0.781952,-0.135269,-0.234109,-0.496404,-0.258658,0.547559,0.706416,0.377198,1.094511
2,-0.711214,-0.735149,-0.219471,1.304258,-1.687165,0.786243,0.238811,-0.088383,2.303177,-0.943421,...,-0.373935,-0.762321,-0.135269,-0.234109,-0.362879,-0.258658,0.547559,0.706416,-1.216577,1.392796
3,1.406046,-0.865547,-0.219471,1.083938,-0.776713,-1.320445,-1.449835,-0.088383,-0.517330,0.941915,...,-0.373935,-0.001184,-0.135269,1.484136,-1.086312,-0.258658,-0.720427,0.706416,-0.647372,1.094511
4,-0.711214,-0.222872,-0.219471,-0.898942,-0.890519,-0.267101,0.238811,-0.088383,-0.517330,-1.122977,...,-0.373935,-0.762321,-0.135269,1.484136,-0.129314,-0.258658,0.547559,0.706416,-0.647372,-0.695200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23775,1.406046,0.634029,-0.219471,-0.752062,0.247546,1.312914,-1.449835,-0.088383,1.363008,-0.763865,...,-0.373935,0.278107,-0.135269,1.484136,-1.111115,-0.258658,0.547559,0.706416,1.174085,-0.695200
23776,1.406046,0.997281,1.188414,0.496418,0.702772,2.366258,0.238811,-0.088383,-0.517330,-0.920977,...,-0.373935,1.603180,-0.135269,-0.234109,0.454393,-0.258658,0.547559,0.706416,1.743291,0.497940
23777,-0.711214,-0.791034,1.188414,0.569858,1.499417,-0.793773,-1.449835,-0.088383,2.303177,-0.763865,...,-0.373935,-0.762321,-0.135269,-0.234109,0.773943,-0.258658,1.815545,0.706416,1.629449,0.497940
23778,-0.711214,-0.409154,-1.627357,0.129218,-0.321487,-1.320445,0.238811,-0.088383,-0.517330,0.941915,...,-0.373935,-0.713245,-0.135269,-0.234109,-0.232042,-0.258658,-0.720427,2.708630,-0.305849,0.199655
23779,-0.711214,0.522260,1.188414,-0.531742,-0.093874,-0.267101,0.238811,-0.088383,1.363008,-1.324977,...,-0.373935,-0.762321,-0.135269,-0.234109,2.112293,-0.258658,0.547559,-1.295798,0.035675,-1.291770

In [61]:
model=RandomForestClassifier(n_estimators=500, criterion='entropy', max_depth=12,min_samples_split=5,min_samples_leaf=2)
model.fit(x_train, y_train)
model.score(x_train, y_train), model.score(x_test, y_test)

(1.0, 0.9999158957106813)

In [62]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [64]:
print("Accuracy Score",accuracy_score(y_test, y_pred))
print("Precision Score",precision_score(y_test, y_pred))
print("Recall Score",recall_score(y_test, y_pred))
print("F1 Score",f1_score(y_test, y_pred))

Accuracy Score 0.9999158957106813
Precision Score 1.0
Recall Score 0.9997750787224472
F1 Score 0.9998875267124058

In [65]:
confusion_matrix(y_test, y_pred)

array([[14888,     0],
       [    2,  8890]], dtype=int64)

In [66]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14888
           1       1.00      1.00      1.00      8892

    accuracy                           1.00     23780
   macro avg       1.00      1.00      1.00     23780
weighted avg       1.00      1.00      1.00     23780