In [21]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r"C:\Users\Dayanand\Desktop\Python\ML Projects\Python_Project_6_SVM.csv")
df

,Quality_Category,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,sulphates,alcohol
0,0,0.30,0.34,1.6,0.049,14,132,0.994,0.49,9.5
1,0,0.23,0.32,8.5,0.058,47,186,0.996,0.40,9.9
2,0,0.28,0.40,6.9,0.050,30,97,0.995,0.44,10.1
3,0,0.32,0.16,7.0,0.045,30,136,0.995,0.47,9.6
4,0,0.27,0.36,20.7,0.045,45,170,1.001,0.45,8.8
...,...,...,...,...,...,...,...,...,...,...
4889,0,0.21,0.29,1.6,0.039,24,92,0.991,0.50,11.2
4890,0,0.32,0.36,8.0,0.047,57,168,0.995,0.46,9.6
4891,0,0.24,0.19,1.2,0.041,30,111,0.993,0.46,9.4
4892,1,0.29,0.30,1.1,0.022,20,110,0.989,0.38,12.8
4893,0,0.21,0.38,0.8,0.020,22,98,0.989,0.32,11.8

In [23]:
df.columns

Index(['Quality_Category', 'volatileacidity', 'citricacid', 'residualsugar',
       'chlorides', 'freesulfurdioxide', 'totalsulfurdioxide', 'density',
       'sulphates', 'alcohol'],
      dtype='object')

In [4]:
df.shape

(4894, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4894 entries, 0 to 4893
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Quality_Category    4894 non-null   int64
 1   volatileacidity     4894 non-null   float64
 2   citricacid          4894 non-null   float64
 3   residualsugar       4894 non-null   float64
 4   chlorides           4894 non-null   float64
 5   freesulfurdioxide   4894 non-null   int64
 6   totalsulfurdioxide  4894 non-null   int64
 7   density             4894 non-null   float64
 8   sulphates           4894 non-null   float64
 9   alcohol             4894 non-null   float64
dtypes: float64(7), int64(3)
memory usage: 382.4 KB

In [7]:
df.describe()

,Quality_Category,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,sulphates,alcohol
count,4894.000000,4894.000000,4894.000000,4894.000000,4894.000000,4894.000000,4894.000000,4894.000000,4894.000000,4894.000000
mean,0.216387,0.278335,0.334146,6.391582,0.045773,35.311606,138.368615,0.994048,0.489904,10.514610
std,0.411823,0.100801,0.121047,5.071695,0.021855,17.019553,42.498278,0.003007,0.114153,1.230665
min,0.000000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987000,0.220000,8.000000
25%,0.000000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.992000,0.410000,9.500000
50%,0.000000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.994000,0.470000,10.400000
75%,0.000000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996000,0.550000,11.400000
max,1.000000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.039000,1.080000,14.200000

In [9]:
df.isnull().sum()

Quality_Category      0
volatileacidity       0
citricacid            0
residualsugar         0
chlorides             0
freesulfurdioxide     0
totalsulfurdioxide    0
density               0
sulphates             0
alcohol               0
dtype: int64

In [22]:
df.corr()

,Quality_Category,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,sulphates,alcohol
Quality_Category,1.000000,-0.068957,-0.035752,-0.116420,-0.182843,-0.023122,-0.161641,-0.280778,0.047611,0.384550
volatileacidity,-0.068957,1.000000,-0.151219,0.064970,0.071244,-0.096971,0.090255,0.026502,-0.035215,0.066148
citricacid,-0.035752,-0.151219,1.000000,0.094453,0.114579,0.094179,0.121674,0.153802,0.062614,-0.076202
residualsugar,-0.116420,0.064970,0.094453,1.000000,0.088498,0.298840,0.401097,0.834798,-0.026678,-0.449915
chlorides,-0.182843,0.071244,0.114579,0.088498,1.000000,0.101402,0.198737,0.255033,0.016735,-0.360112
freesulfurdioxide,-0.023122,-0.096971,0.094179,0.298840,0.101402,1.000000,0.615707,0.294183,0.059374,-0.249988
totalsulfurdioxide,-0.161641,0.090255,0.121674,0.401097,0.198737,0.615707,1.000000,0.530855,0.134523,-0.448597
density,-0.280778,0.026502,0.153802,0.834798,0.255033,0.294183,0.530855,1.000000,0.071343,-0.775374
sulphates,0.047611,-0.035215,0.062614,-0.026678,0.016735,0.059374,0.134523,0.071343,1.000000,-0.017295
alcohol,0.384550,0.066148,-0.076202,-0.449915,-0.360112,-0.249988,-0.448597,-0.775374,-0.017295,1.000000

In [3]:
x=df.drop("Quality_Category", axis=1)
x

,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,sulphates,alcohol
0,0.30,0.34,1.6,0.049,14,132,0.994,0.49,9.5
1,0.23,0.32,8.5,0.058,47,186,0.996,0.40,9.9
2,0.28,0.40,6.9,0.050,30,97,0.995,0.44,10.1
3,0.32,0.16,7.0,0.045,30,136,0.995,0.47,9.6
4,0.27,0.36,20.7,0.045,45,170,1.001,0.45,8.8
...,...,...,...,...,...,...,...,...,...
4889,0.21,0.29,1.6,0.039,24,92,0.991,0.50,11.2
4890,0.32,0.36,8.0,0.047,57,168,0.995,0.46,9.6
4891,0.24,0.19,1.2,0.041,30,111,0.993,0.46,9.4
4892,0.29,0.30,1.1,0.022,20,110,0.989,0.38,12.8
4893,0.21,0.38,0.8,0.020,22,98,0.989,0.32,11.8

In [4]:
y=df["Quality_Category"]
y

0       0
1       0
2       0
3       0
4       0
       ..
4889    0
4890    0
4891    0
4892    1
4893    0
Name: Quality_Category, Length: 4894, dtype: int64

In [5]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2)

In [6]:
x_train.shape, x_test.shape

((3915, 9), (979, 9))

In [7]:
cols=x.columns
cols

Index(['volatileacidity', 'citricacid', 'residualsugar', 'chlorides',
       'freesulfurdioxide', 'totalsulfurdioxide', 'density', 'sulphates',
       'alcohol'],
      dtype='object')

In [8]:
from sklearn.preprocessing import RobustScaler

In [9]:
x_train=RobustScaler().fit_transform(x_train)

In [10]:
x_train=pd.DataFrame(x_train, columns= [cols])
x_train

,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,sulphates,alcohol
0,0.000000,-0.153846,-0.382716,-1.285714,-0.043478,0.000000,-0.50,0.000000,0.105263
1,-0.545455,0.076923,-0.444444,0.500000,-0.260870,0.733333,0.25,-0.285714,-0.736842
2,-0.545455,-0.076923,0.259259,0.714286,-0.086957,1.283333,0.50,0.857143,0.000000
3,-0.727273,1.000000,-0.111111,0.214286,1.000000,0.533333,0.00,1.071429,0.421053
4,0.272727,0.384615,-0.456790,-0.571429,0.000000,-0.133333,-0.75,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...
3910,-0.272727,0.615385,-0.135802,-0.571429,-0.739130,-0.416667,0.25,0.428571,-0.368421
3911,-0.181818,1.153846,0.123457,1.857143,0.043478,0.800000,0.00,-0.071429,-0.368421
3912,0.363636,0.307692,-0.086420,-1.357143,-0.608696,1.066667,-0.50,1.357143,0.789474
3913,-0.454545,-0.384615,0.407407,0.928571,-0.347826,-0.383333,0.50,0.357143,-0.473684
3914,0.272727,1.615385,-0.444444,-0.214286,0.304348,0.966667,-0.50,0.857143,0.000000

In [11]:
x_test=RobustScaler().fit_transform(x_test)
x_test=pd.DataFrame(x_test, columns= [cols])
x_test

,volatileacidity,citricacid,residualsugar,chlorides,freesulfurdioxide,totalsulfurdioxide,density,sulphates,alcohol
0,0.083333,-0.454545,-0.397516,-0.551724,-0.409091,-0.186441,-0.75,0.214286,0.842105
1,0.166667,-0.272727,-0.273292,-0.275862,-0.363636,-0.440678,-0.75,-0.500000,0.684211
2,0.000000,0.000000,-0.447205,0.413793,-0.500000,-0.966102,-1.00,-0.142857,0.894737
3,-1.000000,-1.272727,-0.434783,0.344828,-0.181818,-0.728814,-0.50,0.428571,0.473684
4,0.916667,1.727273,0.857143,0.137931,1.272727,0.508475,1.00,-0.285714,-0.789474
...,...,...,...,...,...,...,...,...,...
974,0.666667,0.090909,0.596273,-0.413793,0.545455,0.661017,0.75,-0.571429,-0.052632
975,0.416667,1.545455,0.248447,-0.551724,-0.363636,-0.711864,0.00,-1.000000,0.631579
976,0.333333,1.363636,0.372671,-0.827586,-0.681818,0.000000,-0.25,-0.357143,0.631579
977,-0.166667,0.181818,-0.037267,-0.689655,0.136364,0.033898,-0.25,-0.642857,0.157895
978,0.583333,-0.909091,-0.409938,-1.034483,-0.727273,-0.745763,-1.25,-0.714286,1.157895

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

In [17]:
models=[LogisticRegression, KNeighborsClassifier, SVC, DecisionTreeClassifier, RandomForestClassifier, GaussianNB]
for mod in models:
    model=mod()
    model.fit(x_train, y_train)
    print(mod, model.score(x_train, y_train), model.score(x_test, y_test))

<class 'sklearn.linear_model._logistic.LogisticRegression'> 0.7971902937420179 0.8089887640449438
<class 'sklearn.neighbors._classification.KNeighborsClassifier'> 0.8779054916985951 0.8110316649642493
<class 'sklearn.svm._classes.SVC'> 0.8234993614303959 0.8130745658835546
<class 'sklearn.tree._classes.DecisionTreeClassifier'> 1.0 0.763023493360572
<class 'sklearn.ensemble._forest.RandomForestClassifier'> 1.0 0.8539325842696629
<class 'sklearn.naive_bayes.GaussianNB'> 0.7279693486590039 0.7129724208375894

In [25]:
#Parameter Tuning with SVC

In [26]:
for i in range(1,100,10):
    model=SVC(C=i)
    model.fit(x_train, y_train)
    print(i, model.score(x_train, y_train), model.score(x_test, y_test))

1 0.8234993614303959 0.8130745658835546
11 0.8551724137931035 0.8140960163432074
21 0.8636015325670499 0.8202247191011236
31 0.8697318007662835 0.8202247191011236
41 0.8743295019157088 0.81511746680286
51 0.8796934865900383 0.8120531154239019
61 0.8827586206896552 0.8120531154239019
71 0.8863346104725415 0.8110316649642493
81 0.8891443167305236 0.8130745658835546
91 0.8914431673052363 0.8110316649642493

In [28]:
model = SVC(C=31)
model.fit(x_train, y_train)
model.score(x_train, y_train), model.score(x_test, y_test)

(0.8697318007662835, 0.8202247191011236)